# Generated by Django 4.0.2 on 2022-05-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaddress',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
